### ISSUE TITLE
Generische Benutzeraccounts

### ISSUE THREAD

**Issue by merkrafter** [AlexKue/SWEP#1]
Erstellen des Datenbackends für Benutzer mit folgenden Attributen:
 + ID (*fänd ich sinnvoll, da sich Namen und Mail-Adresse evtl. ändern*)
 + Nutzername (*Anzeigename, um E-Mail-Adresse nicht zu veröffentlichen*)
 + E-Mail-Adresse (*zum Zurücksetzen des Passworts*)
 + Passworthash
 + Salt

Die anderen Attribute wie bearbeitete Aufgaben und deren Status dann später?

**Comment by AlexKue** [comment]
Ja, das sollten eigentlich die wichtigsten sein. Die bearbeiteten Aufgaben stehen am Ende sowieso bestimmt nichtmal im User-Model, sondern in einem eigenem Table. 
Und die Passwort-Geschichte regelt Rails mit BCrypt auch bereits für uns.

**Comment by AlexKue** [comment]
Zum Model stehen nun 2 Fragen offen:
- Was für eine Maximallänge für den Anzeigenamen wollen wir zulassen ich habe blind einfach mal 50 eingetippt. Immerhin wird der Name ja angezeigt, da sind zu lange Namen etwas unschön denk ich mal.
- Minimale Passwortlänge?

**Comment by MisterDerpie** [comment]
Ich halte 50 Zeichen für angemessen.
Die minimale Passwortlänge von 8 Zeichen sehe ich ebenfalls als angemessen an.

**Comment by MisterDerpie** [comment]
Nach langer Diskussion (< 1 Minute, keine Diskussion) konnten wir uns auf die von Alex bereits voreingestellten Parameter (Nutzername <= 50 Zeichen, E-Mail Adresse <= 255 Zeichen) einigen.
