### ISSUE TITLE
Einrichten einer zweiten (Uni-)Datenbank

### ISSUE THREAD

**Issue by merkrafter** [AlexKue/SWEP#10]
- [ ] **Rechte einstellen**
- [x] Uni-Datenbank erstellen
- [x] Schema laden
- [x] Daten laden
- [x] Verbindung zwischen Rails und DB herstellen

**Comment by MisterDerpie** [comment]
Wie in #34 beschrieben lässt sich dies folgendermaßen lösen:
Kurzform: Die Daten dürfen nicht den Owner des Rails ausführenden Nutzers haben. Deshalb als Postgres erstellen.

Die komplette Anleitung findet sich in [Issue 34, Kommentar](https://github.com/AlexKue/SWEP/pull/34#issuecomment-509391418)

oder hier:
Damit wir die UniDB mit read-only Rechten reinladen, muss diese vom Nutzer Postgres erstellt werden. Der Eigentümer hat sonst immer die Rechte seine eigenen Tabellen zu löschen.
Dafür folgende Anleitung:

Um die UniDB Daten reinzuladen, weiterhin in Postgres:
`$ sudo -u postgres createdb unidb`
Nun müssen die .SQL Daten für die unidb geladen werden (`MSSQL.schema.sql`, `MSSQL.daten.sql`).
Dafür muss vorher die Kodierung auf UTF-8 geändert werden. Um die Kodierung herauszufinden kann der Befehl 
`$ file MSSQL.schema.sql` benutzt werden (.daten analog).
Die Kodierung ist zum Zeitpunkt dieser Anleitung `ISO-8859-1`. Zum ändern folgenden Befehl auf beiden Dateien (Achtung: Es wird vom aktuellen Verzeichnis ausgegangen) aufrufen:
`$ iconv -f ISO-8859-1 -t UTF-8 -o MSSQLschemaUTF8.sql MSSQL.schema.sql`
`$ iconv -f ISO-8859-1 -t UTF-8 -o MSSQLdatenUTF8.sql MSSQL.daten.sql`

Da die Daten Datei leider fehlerhaft ist, muss in Zeile 3-9 nach `DELETE` noch `FROM` hinzugefügt werden, bsp: `DELETE Studenten;` => `DELETE FROM Studenten;`

Jetzt können die Dateien in die unidb geladen werden, dafür:
`$ sudo -u postgres psql -d unidb --file=MSSQLschemaUTF8.sql`
`$ sudo -u postgres psql -d unidb --file=MSSQLdatenUTF8.sql `

Jetzt noch für den Nutzer 'sqrrl' (das ist der Nutzername unseres Nutzers) den DB Zugriff erlauben. Die Befehle stehen unten, hier nur die Erklärungen:
[Nach dieser Anleitung](https://riptutorial.com/postgresql/example/29300/create-read-only-user) kann der Nutzer nun die Rechte nur noch zum Lesen erhalten.
Zusätzlich muss jedoch noch [`CREATE TABLE`](https://aws.amazon.com/blogs/database/managing-postgresql-users-and-roles/) entzogen werden:

`$ sudo -u postgres psql unidb`
```bash
unidb=# CREATE USER sqrrl;
unidb=# GRANT CONNECT ON DATABASE unidb TO sqrrl;
unidb=# GRANT USAGE ON SCHEMA public TO sqrrl;
unidb=# GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO sqrrl;
unidb=# GRANT SELECT ON ALL TABLES IN SCHEMA public TO sqrrl;
unidb=# REVOKE CREATE ON SCHEMA public FROM PUBLIC;
```
oder zum Copy & Pasten
`sudo -u postgres psql unidb`
```pgsql
CREATE USER sqrrl;
GRANT CONNECT ON DATABASE unidb TO sqrrl;
GRANT USAGE ON SCHEMA public TO sqrrl;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO sqrrl;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO sqrrl;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
```
## Sollte die Datenbank neu aufgesetzt werden
Das heißt sie existierte bereits in irgendeiner Form, eventuell erstellt von dem Nutzer `sqrrl`, so muss dies ausgeführt werden um auf den Nutzer `postgres` zu updaten.
Dafür in die Postgres Shell mit
`$ sudo -u postgres psql`
`postgres=# DROP DATABASE unidb;`
`postgres=# DROP OWNED BY user_name;'`
`postgres=# DROP USER user_name;`
dann ist der User gelöscht. Er kann nun mit den korrekten Rechten angelegt werden. Dafür diese Anleitung von ganz oben lesen.


Dateien aus:
https://db.in.tum.de/teaching/bookDBMSeinf/daten/skripteMSSQL/MSSQL.schema.sql
https://db.in.tum.de/teaching/bookDBMSeinf/daten/skripteMSSQL/MSSQL.daten.sql
