### ISSUE TITLE
Dozentenview: Aufgaben erstellen

### ISSUE THREAD

**Issue by merkrafter** [AlexKue/SWEP#11]
Aufgaben zusammen mit 

- Titel, 
- Beschreibung, 
- Übungsserie und 
- Referenzquerys 
- [x] im Frontend erstellen und 
- [x] in die DB schreiben.

**Comment by MisterDerpie** [comment]
Die angesprochenen Dinge sind quasi-fertig.
Es fehlt:
- Warning, falls eine Query keine Daten generiert / das Gleiche tut wie eine andere Query
- Fehler vom Server schicken, falls die Query selbst nicht fehlerfrei ist (Anmerkung: Im Frontend muss diesbezüglich nichts geändert werden, sollte der Server die Fehler im gleichen Format wie bisher schicken)

**Comment by MisterDerpie** [comment]
... leider den falschen Knopf erwischt, es sollte nicht geschlossen werden, da noch Inhalt fehlt
