### ISSUE TITLE
Verringerung der gesendeten Daten in ExercisesList

### ISSUE THREAD

**Issue by MisterDerpie** [AlexKue/SWEP#15]
Unter [GET api/categories/:category_id/exercises](https://github.com/AlexKue/SWEP/wiki/API-Endpoints#get-apicategoriescategory_idexercises) soll nur der `Titel` und die `ID` mitgeschickt werden.
Der Rest wird beim Frontend erst bei konkreterem Aufruf reingeladen.
Dies verringert den entstehenden Overhead durch das Menü

**Comment by AlexKue** [comment]
Gerade fällt mir auf, dass ich mir nun garnicht mehr so sicher bin, was jetzt tatsächlich verschickt werden soll. Hier meinst du ja Titel und ID reichen, aber in https://github.com/AlexKue/SWEP/pull/22#issuecomment-507052584 wolltest du die Points noch mit drinnen haben.

Kann die Issue nun (da #22 ja nun den Exercise-Index geregelt hat und gemerged ist) geschlossen werden oder soll noch was reduziert werden?

**Comment by MisterDerpie** [comment]
In der Tat vernachlässigte ich zu dem Zeitpunkt des anfertigens die Punkte, da ich im Kopf noch den Standardwert (und nicht veränderbar) 1 hatte. Entsprechend ist das hier hinfällig und wird geschlossen.
