### ISSUE TITLE
Rückgabe von Fehlermeldungen fehlt

### ISSUE THREAD

**Issue by MisterDerpie** [AlexKue/SWEP#18]
Es fehlt die Rückgabe von Fehlermeldungen in den Update Funktionen

**Comment by AlexKue** [comment]
Sollte nun per Commits

- e9377eeb6644ddb97410295e392e900a99d1578f
- c5f197f732ca3c9a01d8155f6909ec20fa55e7ac
- 580017d87005be01ba45051dd326f374d99278f8
- bebdc427478d61dc4952c411f9a2c31202d6ca05

gefixt sein.
