### ISSUE TITLE
Webseite stürzt ab, wenn in der Antwort auf POST api/exercises/:id/solve result==null ist

### ISSUE THREAD

**Issue by merkrafter** [AlexKue/SWEP#27]
Steps to reproduce:
1. Erstelle als Dozent eine Aufgabe ohne hinterlegte Query
2. Reiche als Student eine Query für besagte Aufgabe ein
Ergebnis: Der Server schickt durch einen Bug die JSON-Antwort `result:null`, das Frontend verbleibt komplett weiß, es gibt Fehlermeldungen in der JS-Konsole.

Dieser Fehler sollte selbstverständlich serverseitig ausgeschlossen werden, aber womöglich ist auch ein Test im Frontend keine schlechte Idee.

**Comment by MisterDerpie** [comment]
Ich behandle im Frontend Fehler grundsätzlich so, wie ich das bereits zu Alex schrieb. Erwartet wird ein Array vom Server, in dem die Einträge Fehlermeldungen vom Typ String sind.
Eine alternative Fehlerbehandlung kann ich aber dennoch einbauen, wenngleich das nicht Ziel der Sache ist (wenn der Server "abstürzt" ist es in meinen Augen legitim, dass die Website es auch tut, denn es passierte eine Abfolge von Dingen die so nicht zu geschehen hat).
Werde mich morgen dran setzen.

**Comment by merkrafter** [comment]
Es gibt nun einen entsprechenden Hotfix-Branch, der das serverseitige Problem löst.

**Comment by MisterDerpie** [comment]
Sehr gut.
Die Frage ist an der Stelle, ob das Verhalten beschrieben sein soll. Eine vernünftige Fehlerausgabe außer "Etwas ist schief gelaufen" wird nicht möglich sein, da ich nicht in Erfahrung bringen kann, weshalb der Fehler entstanden ist (entsprechende Information wird vom Server nicht mitgeliefert).
Ferner:
Wie besprochen ist das gewünschte Verhalten bei "keiner Query", dass sämtliche Antworten akzeptiert werden (entsprechend sollten diese dann auf den Stand "unsicher" gesetzt werden, als mögliches Szenario könnte diese Aufgabe ein Quiz sein, welches der Dozent dann auswertet).
