### ISSUE TITLE
Automatische Korrektheitserkennung fehlerhaft

### ISSUE THREAD

**Issue by MisterDerpie** [AlexKue/SWEP#28]
Die automatische Korrektheitserkennung funktioniert nicht zuverlässig und / oder fehlerhaft, jedenfalls ist die Sicherheit nicht gut genug.

Als Test sei die UniDB mit den Standarddaten bepackt, folgende Abläufe:
- Als Dozent einloggen
- Übungsserie erstellen
- Übung erstellen
- Query 1 hinterlegen: `SELECT * FROM studenten WHERE name='Carnap';`
- Query 2 hinterlegen: `SELECT * FROM studenten where name='Feuerbach'`
- Ausloggen

- Als Student einloggen
- Auf die entsprechende Aufgabe gehen
- Query `SELECT * FROM studenten WHERE name='Carnap' or name='Feuerbach'` 

Dies resultiert in `solved: false`, obwohl das Ergebnis richtig ist.

**Comment by merkrafter** [comment]
Der eigentliche Fehler ist dann aber, dass noch keine Kontrolle implementiert ist, ob alle Querys des Dozenten äquivalent sind. Dass die Studentenquery abgelehnt wird, ist hingegen richtig.

**Comment by MisterDerpie** [comment]
Dies funktioniert immer noch nicht bzw. macht es die Aufgabe unlösbar.
Reproduzierbar
- Hinterlege mehrere Queries mit unterschiedlichen Ergebnissen
- Versuche die Aufgabe mit einer der Queries zu lösen
Wenigstens ist notwendig, dass die Aufgabe sich mit der zuerst hinterlegten Query lösen lässt.
