### ISSUE TITLE
Sanitize explain_based_checker

### ISSUE THREAD

**Issue by merkrafter** [AlexKue/SWEP#29]
Hier werden die Querys einfach ungeprüft auf die Datenbank losgelassen; das darf so nicht sein. Entsprechende `TODO`s stehen an den entsprechenden Stellen.

**Comment by MisterDerpie** [comment]
Da der Checker in e725e21503a7c2ec07b314d3a535ca65fc550f1a deaktiviert wurde ist das hier hinfällig.
