### ISSUE TITLE
Falsche Tabellendarstellung bei Hintereinanderausführung ähnlicher Querys

### ISSUE THREAD

**Issue by merkrafter** [AlexKue/SWEP#39]
Man gebe Folgendes ein und schicke es ab:
```SQL
SELECT * FROM hören, studenten WHERE hören.matrnr = studenten.matrnr;
```

Anschließend ändere man die Query zu Folgendem und schicke sie ab:
```SQL
SELECT vorlnr, name FROM hören, studenten WHERE hören.matrnr = studenten.matrnr;
```

Das Ergebnis ist eine Tabelle mit den Spalten matrnr | vorlnr | name, wobei der Name in vorlnr steht und die Spalte name leer bleibt.

**Comment by MisterDerpie** [comment]
Behoben in 68ed2897bc6a43823b326ea59e7727d683763648
