### ISSUE TITLE
Sonderzeichen in E-Mails nicht möglich

### ISSUE THREAD

**Issue by MisterDerpie** [AlexKue/SWEP#6]
Eine Registrierung mit Sonderzeichen (ä, ö, ü) ist derzeit nicht möglich, der Server lehnt mit ungültiger E-Mail ab.

Ferner werden folgende E-Mail Adressen aus der englischen Wikipedia (siehe https://en.wikipedia.org/wiki/Email_address#Validation_and_verification) ebenfalls als falsch erkannt:

`"john..doe"@example.org`
`" "@example.org`

**Comment by merkrafter** [comment]
Einige E-Mail-Adressen werden nicht zugelassen, weil sich nicht alle Provider vollständig an Standards halten und man häufig den robusteren Weg wählt.

**Comment by MisterDerpie** [comment]
Da bin ich bei dir. Die Frage ist, ob wir Sonderzeichen zulassen sollten oder nicht. Es ist inzwischen nicht unüblich diese in E-Mail Adressen zu haben (ich besaß selbst zeitweise eine Domain mit Sonderzeichen), oder ob wir das als "wontfix" labeln und dicht machen.

**Comment by MisterDerpie** [comment]
@AlexKue @merkrafter ich möchte nochmal auf diese Issue aufmerksam machen, da sie (sofern hier kein Bedarf besteht) geschlossen werden kann.
Wenngleich ich wenigstens deutsche Sonderzeichen(ä, ö, ü) zulassen wollen würde.
